services:
  mail:
    restart: on-failure
    image: haravich/fake-smtp-server
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - template

  backend:
    image: template-backend:latest
    environment:
      DB_HOST: ${DB_HOST:?error}
      DB_PORT: ${DB_PORT:?error}
      DB_NAME: ${DB_NAME:?error}
      DB_SCHEMA: ${DB_SCHEMA:?error}
      DB_USER: ${DB_USER:?error}
      DB_PASSWORD: ${DB_PASSWORD:?error}
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - template

  migrator:
    image: template-migrator:latest
    environment:
      DB_HOST: ${DB_HOST:?error}
      DB_PORT: ${DB_PORT:?error}
      DB_NAME: ${DB_NAME:?error}
      DB_SCHEMA: ${DB_SCHEMA:?error}
      DB_USER: ${DB_USER:?error}
      DB_PASSWORD: ${DB_PASSWORD:?error}
    env_file:
      - .env
    networks:
      - template

  frontend:
    image: template-frontend:latest
    environment:
      API_URL: ${API_URL:?error}
      DB_HOST: ${DB_HOST:?error}
      DB_PORT: ${DB_PORT:?error}
      DB_NAME: ${DB_NAME:?error}
      DB_SCHEMA: ${DB_SCHEMA:?error}
      DB_USER: ${DB_USER:?error}
      DB_PASSWORD: ${DB_PASSWORD:?error}
      AUTH_SECRET: ${AUTH_SECRET:?error}
      AUTH_DISCORD_ID: ${AUTH_DISCORD_ID:?error}
      AUTH_DISCORD_SECRET: ${AUTH_DISCORD_SECRET:?error}
      AUTH_TRUST_HOST: true
      AUTH_URL: ${AUTH_URL:?error}
      SMTP_HOST: ${SMTP_HOST:?error}
      SMTP_PORT: ${SMTP_PORT:?error}
      SMTP_SECURE: ${SMTP_SECURE:?error}
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - template

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - template-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - template
    restart: unless-stopped

  pgadmin:
    image: elestio/pgadmin:REL-8_12
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - template-pgadmin:/var/lib/pgadmin
    ports:
      - "5050:5050"
    networks:
      - template
    restart: always

networks:
  template:
    driver: bridge

volumes:
  template-postgres:
  template-pgadmin:
